networks:
  signherenet:
    name: signherenet

services:
  logging:
    container_name: logging
    image: docker.io/timberio/vector:0.35.0-debian
    networks:
      - signherenet
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: no
    environment: [
#      "VECTOR_LOG=debug"
    ]
    volumes:
      - ./support/development/vectordev:/etc/vectordev
      - ./logs:/tmp/logs
    command: ["--config-toml", "/etc/vectordev/demo.vector.toml", "--watch-config"]