# Vector Configuration File
[api]
enabled = true

# Define sources
[sources.logfile_source]
type = "file"
include = [ "/tmp/logs/tester.log" ]

[transforms.filter_logfile]
type = "filter"
inputs = ["logfile_source"]
condition = 'includes(["DEBUG", "INFO", "WARN", "ERROR"], parse_json!(string!(.message)).level)'

[transforms.elastic]
type = "remap"
inputs = ["filter_logfile"]
source = '''
o_host = .host
. = parse_json!(string!(.message))
.host = o_host
.host.name = get_hostname() ?? "unknown-host"
.fields.env = "gary-test"
.fields.op = false
.fields.app_id = get_env_var("APP_ID") ?? ""
.category = .logger_name
.thread = .thread_name
.agent.name = "vector"
.agent.type = "vector"
del(.level_value)
del(.@version)
del(.logger_name)
del(.thread_name)
'''

[sinks.stdout]
type = "console"
inputs = [ "elastic" ]
encoding.charset = "UTF-8"
encoding.codec = "json"

## elastic connection
#[sinks.nigel_pos_elastic]
#api_version = "v8"
#type = "elasticsearch"
#inputs = [ "elastic" ]
#endpoints = [ "https://nigel-pos.es.us-east-2.aws.elastic-cloud.com:9243" ]
#bulk.action = "create"
#buffer.max_events = 100
#buffer.type = "memory"
#mode = "data_stream"
#data_stream.namespace = "default"
#data_stream.type = "logs"
#data_stream.dataset = "vector-cloud-demo"
#encoding.timestamp_format = "rfc3339"
#request.headers = { "Authorization" = "ApiKey QnBsOWlvMEJYa3BURHNZUnpoSGs6ZXFtakFKRGlUMDZYdEd0YVpNVDBXdw==" }
